"""add missing document columns

Revision ID: 3a848b24a044
Revises: b971bea26182
Create Date: 2026-05-01 16:46:52.553722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a848b24a044'
down_revision: Union[str, None] = 'b971bea26182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('impact_tier', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('affected_audience', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_documents_published_at'), table_name='documents')
    op.create_index(op.f('ix_documents_impact_tier'), 'documents', ['impact_tier'], unique=False)
    op.drop_column('documents', 'expiry_date')
    op.drop_column('documents', 'effective_date')
    op.drop_column('documents', 'published_at')
    op.drop_column('users', 'profile_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('effective_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_documents_impact_tier'), table_name='documents')
    op.create_index(op.f('ix_documents_published_at'), 'documents', ['published_at'], unique=False)
    op.drop_column('documents', 'affected_audience')
    op.drop_column('documents', 'impact_tier')
    # ### end Alembic commands ###
