"""Initial schema

Revision ID: b971bea26182
Revises: 
Create Date: 2026-04-08 09:44:40.829430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b971bea26182'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_digests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('summary_hindi', sa.Text(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('has_updates', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('llm_model_used', sa.String(length=100), nullable=True),
    sa.Column('llm_cost_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'date', name='uq_category_date')
    )
    op.create_index(op.f('ix_category_digests_category'), 'category_digests', ['category'], unique=False)
    op.create_index(op.f('ix_category_digests_date'), 'category_digests', ['date'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('region_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('crawler_class', sa.String(length=255), nullable=False),
    sa.Column('crawler_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('digests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('category_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery_channel', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('fetch_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('clean_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_hindi', sa.Text(), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_category', sa.String(length=50), nullable=True),
    sa.Column('regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('departments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_number', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('simhash', sa.String(length=64), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('duplicate_of', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_categories', 'documents', ['categories'], unique=False, postgresql_using='gin')
    op.create_index('idx_documents_regions', 'documents', ['regions'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_primary_category'), 'documents', ['primary_category'], unique=False)
    op.create_index(op.f('ix_documents_published_at'), 'documents', ['published_at'], unique=False)
    op.create_index(op.f('ix_documents_ingested_at'), 'documents', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_table('ingest_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('items_fetched', sa.Integer(), nullable=True),
    sa.Column('items_new', sa.Integer(), nullable=True),
    sa.Column('items_duplicate', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingest_log')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_ingested_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_published_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_primary_category'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_index('idx_documents_regions', table_name='documents', postgresql_using='gin')
    op.drop_index('idx_documents_categories', table_name='documents', postgresql_using='gin')
    op.drop_table('documents')
    # ### end Alembic commands ###
