"""Add image_url and image_search_query to documents

Revision ID: fd8bf26a231a
Revises: 3a848b24a044
Create Date: 2026-06-01 00:32:28.853342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8bf26a231a'
down_revision: Union[str, None] = '3a848b24a044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('image_search_query', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'image_search_query')
    op.drop_column('documents', 'image_url')
    # ### end Alembic commands ###
